apiVersion: v1
kind: Service
metadata:
  name: apollo-router
spec:
  selector: {app: apollo-router}
  ports:
  - {name: graphql, port: 4000, targetPort: 4000}
  - {name: health, port: 8088, targetPort: 8088}
